# Objective: The objective of this assignment is to gain practical experience with fundamental operations in TensorFlow, including creating and manipulating matrices, performing arithmetic operations on tensors, and understanding the difference between TensorFlow constants and variables.


## Part 1: Theoretical Question

#### 1. What are the different data structures used in Tensorflow? Give some examples.
Ans. TensorFlow primarily uses two main data structures: tensors and graphs.

Tensors: Tensors are multi-dimensional arrays used to represent data in TensorFlow. They can have various ranks (dimensions) like scalars, vectors, matrices, or higher-dimensional arrays. Tensors can hold numerical values, such as integers or floating-point numbers. Examples of tensors include:

    Scalar (Rank-0 tensor): A single number, e.g., 5.
    Vector (Rank-1 tensor): A 1-dimensional array, e.g., [1, 2, 3].
    Matrix (Rank-2 tensor): A 2-dimensional array, e.g., [[1, 2], [3, 4]].
    Higher-dimensional tensor (e.g., Rank-3, Rank-4, etc.).

Graphs: TensorFlow uses a computational graph to represent and perform operations on tensors. A graph consists of nodes (representing operations) and edges (representing data flow, i.e., tensors). TensorFlow constructs a graph to describe the computations, and then executes it within a session.

#### 2.  How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example.
Ans. TensorFlow Constant: A constant in TensorFlow is a type of tensor whose value cannot be changed after its initialization. It is typically used to represent fixed values in the graph. Once a constant is defined, its value remains the same throughout the execution of the program.
Example:

    import tensorflow as tf
    # Creating a TensorFlow constant
    constant_tensor = tf.constant([1, 2, 3])
    
TensorFlow Variable: A variable in TensorFlow is a type of tensor that can be modified during the execution of the program. Variables are used to store and update values that might change during training, such as model weights.
Example:

    import tensorflow as tf                
    # Creating a TensorFlow variable
    initial_value = [0, 0]
    variable_tensor = tf.Variable(initial_value)


#### 3.  Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow.
Ans. Matrix Addition: In TensorFlow, matrix addition is performed using the tf.add() function or the + operator. The matrices should have the same dimensions for addition to be valid.

    import tensorflow as tf
    # Define two matrices
    matrix_A = tf.constant([[1, 2], [3, 4]])
    matrix_B = tf.constant([[5, 6], [7, 8]])
    # Perform matrix addition
    matrix_sum = tf.add(matrix_A, matrix_B)

Matrix Multiplication: In TensorFlow, matrix multiplication is performed using the tf.matmul() function or the @ operator. The inner dimensions of the matrices must match for multiplication to be valid (e.g., if A is of shape (m, n) and B is of shape (n, p), then C = A @ B will result in a matrix of shape (m, p)).

    import tensorflow as tf
    # Define two matrices
    matrix_C = tf.constant([[1, 2], [3, 4]])
    matrix_D = tf.constant([[5, 6], [7, 8]])
    # Perform matrix multiplication
    matrix_product = tf.matmul(matrix_C, matrix_D)

Element-wise Operations: Element-wise operations in TensorFlow are operations that are performed on corresponding elements of two tensors of the same shape. Element-wise operations include addition, subtraction, multiplication, division, and more. For element-wise operations, the tensors must have the same shape.

    import tensorflow as tf
    # Define two matrices
    matrix_E = tf.constant([[1, 2], [3, 4]])
    matrix_F = tf.constant([[5, 6], [7, 8]])
    # Perform element-wise addition
    elementwise_sum = tf.add(matrix_E, matrix_F)
    # Perform element-wise multiplication
    elementwise_product = tf.multiply(matrix_E, matrix_F)

In [1]:
import tensorflow as tf
# Creating a TensorFlow constant
constant_tensor = tf.constant([1, 2, 3])

# Creating a TensorFlow variable
initial_value = [0, 0]
variable_tensor = tf.Variable(initial_value)

constant_tensor, variable_tensor

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([0, 0])>)

In [2]:
import tensorflow as tf
matrix_A = tf.constant([[1, 2], [3, 4]])
matrix_B = tf.constant([[5, 6], [7, 8]])
# Perform matrix addition
matrix_sum = tf.add(matrix_A, matrix_B)

matrix_C = tf.constant([[1, 2], [3, 4]])
matrix_D = tf.constant([[5, 6], [7, 8]])
# Perform matrix multiplication
matrix_product = tf.matmul(matrix_C, matrix_D)

matrix_E = tf.constant([[1, 2], [3, 4]])
matrix_F = tf.constant([[5, 6], [7, 8]])
# Perform element-wise addition
elementwise_sum = tf.add(matrix_E, matrix_F)
# Perform element-wise multiplication
elementwise_product = tf.multiply(matrix_E, matrix_F)

matrix_sum, matrix_product, elementwise_sum, elementwise_product

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 6,  8],
        [10, 12]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[19, 22],
        [43, 50]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 6,  8],
        [10, 12]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 5, 12],
        [21, 32]])>)

## Part 2: Practical Implementation
    
    Task 1: Creating and Manipulating Matrices
    
#### 1.  Create a normal matrix A with dimensions 2x2, using TensorFlow's random_normal function. Display the values of matrix A.
#### 2. Create a Gaussian matrix B with dimensions x, using TensorFlow's truncated_normal function. Display the values of matrix B.
#### 3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 2 and a standard deviation of 0.x, using TensorFlow's random.normal function. Display the values of matrix C.
#### 4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D.
#### 5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

    Talk 2: Performing Additional Matrix Operations
    
#### 1. Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform function.
#### 2. Calculate the transpose of matrix F and store the result in matrix G.
#### 3. Calculate the elementDwise exponential of matrix F and store the result in matrix H.
#### 4. Create a matrix I by concatenating matrix F and matrix G horizontally.
#### 5. Create a matrix J by concatenating matrix F and matrix H vertically.

In [4]:
import tensorflow as tf

# Task 1: Creating and Manipulating Matrices

# 1. Create a normal matrix A with dimensions 2x2, using TensorFlow's random_normal function.
matrix_A = tf.random.normal(shape=(2, 2))
print("Matrix A:")
print(matrix_A.numpy())

# 2. Create a Gaussian matrix B with dimensions 2x2, using TensorFlow's truncated_normal function.
matrix_B = tf.random.truncated_normal(shape=(2, 2))
print("Matrix B:")
print(matrix_B.numpy())

# 3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 2 and a standard deviation of 0.x,
#    using TensorFlow's random.normal function.
matrix_C = tf.random.normal(shape=(2, 2), mean=2.0, stddev=0.1)
print("Matrix C:")
print(matrix_C.numpy())

# 4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D.
matrix_D = tf.add(matrix_A, matrix_B)
print("Matrix D (Result of addition):")
print(matrix_D.numpy())

# 5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.
matrix_E = tf.matmul(matrix_C, matrix_D)
print("Matrix E (Result of multiplication):")
print(matrix_E.numpy())

# Task 2: Performing Additional Matrix Operations

# 1. Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform function.
matrix_F = tf.random.uniform(shape=(2, 2))
print("Matrix F:")
print(matrix_F.numpy())

# 2. Calculate the transpose of matrix F and store the result in matrix G.
matrix_G = tf.transpose(matrix_F)
print("Matrix G (Transpose of F):")
print(matrix_G.numpy())

# 3. Calculate the element-wise exponential of matrix F and store the result in matrix H.
matrix_H = tf.exp(matrix_F)
print("Matrix H (Element-wise exponential of F):")
print(matrix_H.numpy())

# 4. Create a matrix I by concatenating matrix F and matrix G horizontally.
matrix_I = tf.concat([matrix_F, matrix_G], axis=1)
print("Matrix I (Horizontal concatenation of F and G):")
print(matrix_I.numpy())

# 5. Create a matrix J by concatenating matrix F and matrix H vertically.
matrix_J = tf.concat([matrix_F, matrix_H], axis=0)
print("Matrix J (Vertical concatenation of F and H):")
print(matrix_J.numpy())

Matrix A:
[[-2.5860367  -1.5731997 ]
 [ 1.1998386  -0.42172316]]
Matrix B:
[[-1.0128514   1.7534056 ]
 [ 1.3891175   0.33503336]]
Matrix C:
[[1.9655114 2.0112004]
 [1.9416394 2.1508543]]
Matrix D (Result of addition):
[[-3.598888    0.18020582]
 [ 2.588956   -0.0866898 ]]
Matrix E (Result of multiplication):
[[-1.866746    0.17984605]
 [-1.4192753   0.1634376 ]]
Matrix F:
[[0.5170368  0.49729586]
 [0.16028428 0.21580803]]
Matrix G (Transpose of F):
[[0.5170368  0.16028428]
 [0.49729586 0.21580803]]
Matrix H (Element-wise exponential of F):
[[1.6770508 1.6442689]
 [1.1738446 1.2408642]]
Matrix I (Horizontal concatenation of F and G):
[[0.5170368  0.49729586 0.5170368  0.16028428]
 [0.16028428 0.21580803 0.49729586 0.21580803]]
Matrix J (Vertical concatenation of F and H):
[[0.5170368  0.49729586]
 [0.16028428 0.21580803]
 [1.6770508  1.6442689 ]
 [1.1738446  1.2408642 ]]
