In [1]:
#sort, search and Counting functions

In [2]:
import numpy as np

In [8]:
arr = np.array([4,3,2,5,6,7,4])

In [10]:
np.sort(arr)
arr

array([4, 3, 2, 5, 6, 7, 4])

In [7]:
arr.sort()#sort inplace
arr

array([2, 3, 4, 4, 5, 6, 7])

In [11]:
np.searchsorted(arr,6)

4

In [12]:
arr1 = np.array([0,324,645,65,6,6,0,234])

In [13]:
np.count_nonzero(arr1)

6

In [18]:
np.where(arr1>0)#index of the element where condtion is true

(array([1, 2, 3, 4, 5, 7]),)

In [20]:
np.extract(arr1>0,arr1)#array where condition is true

array([324, 645,  65,   6,   6, 234])

In [21]:
#byte swapping

In [22]:
arr1

array([  0, 324, 645,  65,   6,   6,   0, 234])

In [24]:
arr,arr.byteswap()#inplace = True to get the location

(array([4, 3, 2, 5, 6, 7, 4]),
 array([288230376151711744, 216172782113783808, 144115188075855872,
        360287970189639680, 432345564227567616, 504403158265495552,
        288230376151711744]))

In [25]:
#copies and views

In [27]:
ar = arr
arr[0]=-5
ar,arr

(array([-5,  3,  2,  5,  6,  7,  4]), array([-5,  3,  2,  5,  6,  7,  4]))

In [30]:
b = arr.copy()
arr[-1]= -10
b,arr

(array([  -5,    3,    2,    5,    6,    7, -100]),
 array([ -5,   3,   2,   5,   6,   7, -10]))

In [32]:
arr1
c=arr1.view() #also a shallow copy
arr1[0]=-1
arr1,c

(array([ -1, 324, 645,  65,   6,   6,   0, 234]),
 array([ -1, 324, 645,  65,   6,   6,   0, 234]))

In [33]:
#numpy matrix library

In [34]:
import numpy.matlib as nm

In [35]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [36]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [37]:
nm.eye(2)

matrix([[1., 0.],
        [0., 1.]])

In [38]:
#linear alebra

In [41]:
ar1 = np.random.randint([[2,4],[4,5]]) #np.random.randint(2,4,(4,5))
ar2 = np.random.randint([[2,4],[4,5]])
ar1,ar2

(array([[1, 0],
        [3, 2]]),
 array([[0, 1],
        [3, 4]]))

In [43]:
np.dot(ar1,ar2)

array([[ 0,  1],
       [ 6, 11]])

In [54]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_,dtype=int)
type(list_),type(array_list)

(list, numpy.ndarray)

In [55]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [56]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [57]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [59]:
num_array.shape,num_array.size

((2, 3), 6)