In [1]:
import numpy as np

In [3]:
list(range(5)), list(range(0,10))

([0, 1, 2, 3, 4], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
list(range(0.4,10.2))

TypeError: 'float' object cannot be interpreted as an integer

In [10]:
#arange-even a floating point numbers
np.arange(5)
np.arange(1,10)
np.arange(0.2,10.5)
np.arange(0.2,10.5,0.8)

array([0.2, 1. , 1.8, 2.6, 3.4, 4.2, 5. , 5.8, 6.6, 7.4, 8.2, 9. , 9.8])

In [11]:
#to convert to list
list(np.arange(0.2,10.5,0.8))

[0.2,
 1.0,
 1.8,
 2.6000000000000005,
 3.4000000000000004,
 4.2,
 5.000000000000001,
 5.800000000000001,
 6.6000000000000005,
 7.4,
 8.2,
 9.0,
 9.8]

In [12]:
#np.linspace(a,b,n) - equally dividided n numbers between a and b
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [15]:
#logspace??
np.logspace(1,5,2)

array([1.e+01, 1.e+05])

In [16]:
np.log10(5)

0.6989700043360189

In [21]:
np.zeros(5),np.zeros((3,4)),np.zeros((3,4,2))

(array([0., 0., 0., 0., 0.]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],
 
        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],
 
        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]))

In [22]:
np.zeros((3,2,4,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [23]:
np.ones(3),np.ones((3,4))

(array([1., 1., 1.]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]))

In [24]:
arr = np.ones((3,4))
arr+5,arr*4,arr-6

(array([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]]),
 array([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]]),
 array([[-5., -5., -5., -5.],
        [-5., -5., -5., -5.],
        [-5., -5., -5., -5.]]))

In [25]:
#?empty array where is it used?
np.empty((2,2))

array([[4.64696028e-310, 0.00000000e+000],
       [4.64767058e-310, 4.64767065e-310]])

In [27]:
np.eye(3) #identity matrix - always a square matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
import pandas as pd

In [29]:
pd.DataFrame(arr)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [33]:
#randn-from standard normal distribution
#rand - Create an array of the given shape and populate it with random samples from a uniform distribution over ``[0, 1)``.
np.random.rand(2,3),np.random.randn(2,3)

(array([[0.41520664, 0.51643938, 0.6488833 ],
        [0.17196852, 0.7637768 , 0.67174597]]),
 array([[ 1.50981246, -0.82946582,  0.51406143],
        [ 0.00865462, -0.04894416, -0.88177826]]))

In [37]:
np.random.randint(4,6,(3,3))

array([[5, 5, 5],
       [5, 5, 5],
       [5, 4, 4]])

In [38]:
arr.shape,arr.size

((3, 4), 12)

In [45]:
arr.reshape(4,3) # should always be of same size in able to reshape any array!
#if not sure about the array but sure about rows, columns can use -1 or any negative value
arr.reshape(6,-1)
arr.reshape(-45,6)
arr.reshape(2,2,3)

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [47]:
arr1=np.random.randint(1,10,(5,6))
arr1

array([[9, 1, 8, 6, 3, 8],
       [2, 7, 9, 2, 8, 8],
       [9, 3, 1, 2, 9, 9],
       [7, 7, 4, 3, 7, 1],
       [6, 3, 3, 6, 8, 7]])

In [49]:
#to filter array with value>8
arr1>8
arr1[arr1>8]

array([9, 9, 9, 9, 9])

In [52]:
arr1[0:2,0:2],arr1[3:5,4:],arr1[:3,:2]

(array([[9, 1],
        [2, 7]]),
 array([[7, 1],
        [8, 7]]),
 array([[9, 1],
        [2, 7],
        [9, 3]]))

In [53]:
ar1 = np.random.randint(1,5,(3,3))
ar2 = np.random.randint(2,6,(3,3))

In [57]:
ar1,ar2,ar1+ar2,ar1-ar2,ar1*ar2 #index wise operation even multiply not matrix mult

(array([[3, 1, 1],
        [1, 4, 4],
        [4, 2, 2]]),
 array([[4, 2, 3],
        [3, 2, 3],
        [4, 5, 5]]),
 array([[7, 3, 4],
        [4, 6, 7],
        [8, 7, 7]]),
 array([[-1, -1, -2],
        [-2,  2,  1],
        [ 0, -3, -3]]),
 array([[12,  2,  3],
        [ 3,  8, 12],
        [16, 10, 10]]))

In [58]:
ar1@ar2 #matrix multiplication

array([[19, 13, 17],
       [32, 30, 35],
       [30, 22, 28]])

In [60]:
ar1/0 #does not give error but inf for infinity

/tmp/ipykernel_106/2492459060.py:1: RuntimeWarning: divide by zero encountered in divide
  ar1/0 #does not give error but inf for infinity


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [63]:
np.eye(3)/0

/tmp/ipykernel_106/3887623802.py:1: RuntimeWarning: divide by zero encountered in divide
  np.eye(3)/0
/tmp/ipykernel_106/3887623802.py:1: RuntimeWarning: invalid value encountered in divide
  np.eye(3)/0


array([[inf, nan, nan],
       [nan, inf, nan],
       [nan, nan, inf]])

In [64]:
#broadcasting
ar = np.zeros((3,4))

In [65]:
ar+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [68]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [67]:
ar+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [73]:
b = np.array([[3,4,5]])# can't transponse 1-D array
b,b.T

(array([[3, 4, 5]]),
 array([[3],
        [4],
        [5]]))

In [75]:
ar+b.T

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [84]:
c=ar+b.T
np.sqrt(c),np.log10(c),np.exp(c),np.min(c),np.max(c),c.min(),c.max()

(array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
        [2.        , 2.        , 2.        , 2.        ],
        [2.23606798, 2.23606798, 2.23606798, 2.23606798]]),
 array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
        [0.60205999, 0.60205999, 0.60205999, 0.60205999],
        [0.69897   , 0.69897   , 0.69897   , 0.69897   ]]),
 array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
        [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
        [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]]),
 3.0,
 5.0,
 3.0,
 5.0)