In [1]:
import numpy as np

In [2]:
#Array manipulation

In [3]:
arr = np.random.randint(1,10,(4,4))

In [6]:
arr.reshape(8,2),arr.reshape(2,8),arr.reshape(-1)

(array([[9, 8],
        [5, 6],
        [2, 4],
        [2, 3],
        [5, 5],
        [8, 6],
        [5, 7],
        [3, 8]]),
 array([[9, 8, 5, 6, 2, 4, 2, 3],
        [5, 5, 8, 6, 5, 7, 3, 8]]),
 array([9, 8, 5, 6, 2, 4, 2, 3, 5, 5, 8, 6, 5, 7, 3, 8]))

In [7]:
arr.T

array([[9, 2, 5, 5],
       [8, 4, 5, 7],
       [5, 2, 8, 3],
       [6, 3, 6, 8]])

In [8]:
arr.flatten(),arr.reshape(-1)

(array([9, 8, 5, 6, 2, 4, 2, 3, 5, 5, 8, 6, 5, 7, 3, 8]),
 array([9, 8, 5, 6, 2, 4, 2, 3, 5, 5, 8, 6, 5, 7, 3, 8]))

In [9]:
np.expand_dims(arr,axis=1),np.expand_dims(arr,axis=0),

(array([[[9, 8, 5, 6]],
 
        [[2, 4, 2, 3]],
 
        [[5, 5, 8, 6]],
 
        [[5, 7, 3, 8]]]),
 array([[[9, 8, 5, 6],
         [2, 4, 2, 3],
         [5, 5, 8, 6],
         [5, 7, 3, 8]]]))

In [11]:
data = np.array([[1],[2],[3]])
data

array([[1],
       [2],
       [3]])

In [13]:
np.squeeze(data) #opposite of expand_dims

array([1, 2, 3])

In [15]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [17]:
np.roll(data,2) #new position = index+2

array([[2],
       [3],
       [1]])

In [20]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [21]:
#binary operators

In [23]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))
arr1,arr2

(array([[4, 7, 3, 7],
        [8, 4, 1, 6],
        [6, 8, 6, 9]]),
 array([[1, 9, 6, 4],
        [9, 1, 7, 4],
        [7, 3, 9, 5]]))

In [24]:
arr1+arr2,arr1-arr2,arr1*arr2,arr1/arr2,arr1**arr2

(array([[ 5, 16,  9, 11],
        [17,  5,  8, 10],
        [13, 11, 15, 14]]),
 array([[ 3, -2, -3,  3],
        [-1,  3, -6,  2],
        [-1,  5, -3,  4]]),
 array([[ 4, 63, 18, 28],
        [72,  4,  7, 24],
        [42, 24, 54, 45]]),
 array([[4.        , 0.77777778, 0.5       , 1.75      ],
        [0.88888889, 4.        , 0.14285714, 1.5       ],
        [0.85714286, 2.66666667, 0.66666667, 1.8       ]]),
 array([[        4,  40353607,       729,      2401],
        [134217728,         4,         1,      1296],
        [   279936,       512,  10077696,     59049]]))

In [25]:
~arr1,~arr2

(array([[ -5,  -8,  -4,  -8],
        [ -9,  -5,  -2,  -7],
        [ -7,  -9,  -7, -10]]),
 array([[ -2, -10,  -7,  -5],
        [-10,  -2,  -8,  -5],
        [ -8,  -4, -10,  -6]]))

In [26]:
arr1>arr2

array([[ True, False, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [27]:
#string operations

In [29]:
arr = np.array(['ram','sam','mo'])
arr

array(['ram', 'sam', 'mo'], dtype='<U3')

In [33]:
np.char.upper(arr),np.char.capitalize(arr),np.char.title(arr)

(array(['RAM', 'SAM', 'MO'], dtype='<U3'),
 array(['Ram', 'Sam', 'Mo'], dtype='<U3'),
 array(['Ram', 'Sam', 'Mo'], dtype='<U3'))

In [34]:
#mathematical functions
np.sin(arr1),np.cos(arr1),np.tan(arr1),np.log2(arr1),np.exp(arr1),np.power(arr1,3)

(array([[-0.7568025 ,  0.6569866 ,  0.14112001,  0.6569866 ],
        [ 0.98935825, -0.7568025 ,  0.84147098, -0.2794155 ],
        [-0.2794155 ,  0.98935825, -0.2794155 ,  0.41211849]]),
 array([[-0.65364362,  0.75390225, -0.9899925 ,  0.75390225],
        [-0.14550003, -0.65364362,  0.54030231,  0.96017029],
        [ 0.96017029, -0.14550003,  0.96017029, -0.91113026]]),
 array([[ 1.15782128,  0.87144798, -0.14254654,  0.87144798],
        [-6.79971146,  1.15782128,  1.55740772, -0.29100619],
        [-0.29100619, -6.79971146, -0.29100619, -0.45231566]]),
 array([[2.        , 2.80735492, 1.5849625 , 2.80735492],
        [3.        , 2.        , 0.        , 2.5849625 ],
        [2.5849625 , 3.        , 2.5849625 , 3.169925  ]]),
 array([[5.45981500e+01, 1.09663316e+03, 2.00855369e+01, 1.09663316e+03],
        [2.98095799e+03, 5.45981500e+01, 2.71828183e+00, 4.03428793e+02],
        [4.03428793e+02, 2.98095799e+03, 4.03428793e+02, 8.10308393e+03]]),
 array([[ 64, 343,  27, 343],
      

In [39]:
np.min(arr1),np.max(arr1),np.mean(arr1),np.median(arr1),np.std(arr1),np.var(arr1)

(1, 9, 5.75, 6.0, 2.2407216099581255, 5.020833333333333)

In [44]:
arr1.min(),arr1.max(),arr1.mean(),arr1.std(),arr1.var() #arr1.median() doesn't work

(1, 9, 5.75, 2.2407216099581255, 5.020833333333333)

In [45]:
#arthematic operation

In [46]:
arr1,arr2

(array([[4, 7, 3, 7],
        [8, 4, 1, 6],
        [6, 8, 6, 9]]),
 array([[1, 9, 6, 4],
        [9, 1, 7, 4],
        [7, 3, 9, 5]]))

In [47]:
arr1-arr2, np.subtract(arr1,arr2)

(array([[ 3, -2, -3,  3],
        [-1,  3, -6,  2],
        [-1,  5, -3,  4]]),
 array([[ 3, -2, -3,  3],
        [-1,  3, -6,  2],
        [-1,  5, -3,  4]]))

In [48]:
arr1*arr2,np.multiply(arr1,arr2)

(array([[ 4, 63, 18, 28],
        [72,  4,  7, 24],
        [42, 24, 54, 45]]),
 array([[ 4, 63, 18, 28],
        [72,  4,  7, 24],
        [42, 24, 54, 45]]))

In [49]:
arr1@arr2.T,np.matmul(arr1,arr2.T)

(array([[113,  92, 111],
        [ 74, 107, 107],
        [150, 140, 165]]),
 array([[113,  92, 111],
        [ 74, 107, 107],
        [150, 140, 165]]))

In [50]:
np.mod(arr1,arr2)

array([[0, 7, 3, 3],
       [8, 0, 1, 2],
       [6, 2, 6, 4]])

In [52]:
np.power(arr1,arr2)

array([[        4,  40353607,       729,      2401],
       [134217728,         4,         1,      1296],
       [   279936,       512,  10077696,     59049]])

In [53]:
#statistical

In [54]:
np.mean(arr1),arr1.mean()

(5.75, 5.75)

In [58]:
np.std(arr1),arr1.std(),np.var(arr1),arr1.var()

(2.2407216099581255, 2.2407216099581255, 5.020833333333333, 5.020833333333333)

In [59]:
np.median(arr1),#arr1.median()

(6.0,)