In [1]:
#XGBoost is not present in sklearn have to install it

In [2]:
pip install Xgboost

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.3/200.3 MB 13.8 MB/s eta 0:00:0000:0100:01
Note: you may need to restart the kernel to use updated packages.


# Classification

In [4]:
from sklearn.datasets import make_classification

In [5]:
X,y = make_classification(n_samples=1000,
                            n_features=4,
                            n_informative=2,
                            n_redundant=0,
                            shuffle=False,
                            random_state=0)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.33, random_state=42)

In [8]:
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier

In [11]:
#import xgboost - remember it's not in sklearn
import xgboost as xb

In [12]:
classifier1 = AdaBoostClassifier()

In [13]:
classifier1.fit(X_train,y_train)

AdaBoostClassifier()

In [14]:
y_pred1 = classifier1.predict(X_test)

In [15]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [19]:
acc = accuracy_score(y_test,y_pred1)
conf_mat = confusion_matrix(y_test,y_pred1)
cls_rep = classification_report(y_test,y_pred1)
print(f"{acc}\n{conf_mat}\n{cls_rep}")

0.9242424242424242
[[153  13]
 [ 12 152]]
              precision    recall  f1-score   support

           0       0.93      0.92      0.92       166
           1       0.92      0.93      0.92       164

    accuracy                           0.92       330
   macro avg       0.92      0.92      0.92       330
weighted avg       0.92      0.92      0.92       330



In [20]:
classifier2 = GradientBoostingClassifier()

In [21]:
classifier2.fit(X_train,y_train)

GradientBoostingClassifier()

In [22]:
y_pred2 = classifier2.predict(X_test)

In [23]:
acc = accuracy_score(y_test,y_pred2)
conf_mat = confusion_matrix(y_test,y_pred2)
cls_rep = classification_report(y_test,y_pred2)
print(f"{acc}\n{conf_mat}\n{cls_rep}")

0.9393939393939394
[[153  13]
 [  7 157]]
              precision    recall  f1-score   support

           0       0.96      0.92      0.94       166
           1       0.92      0.96      0.94       164

    accuracy                           0.94       330
   macro avg       0.94      0.94      0.94       330
weighted avg       0.94      0.94      0.94       330



In [24]:
classifier3 = xb.XGBClassifier()

In [25]:
classifier3.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [27]:
y_pred3 = classifier3.predict(X_test)

In [28]:
acc = accuracy_score(y_test,y_pred3)
conf_mat = confusion_matrix(y_test,y_pred3)
cls_rep = classification_report(y_test,y_pred3)
print(f"{acc}\n{conf_mat}\n{cls_rep}")

0.9333333333333333
[[155  11]
 [ 11 153]]
              precision    recall  f1-score   support

           0       0.93      0.93      0.93       166
           1       0.93      0.93      0.93       164

    accuracy                           0.93       330
   macro avg       0.93      0.93      0.93       330
weighted avg       0.93      0.93      0.93       330



# regression

In [29]:
from sklearn.datasets import make_regression

In [31]:
X,y = make_regression(n_samples=1000,
                            n_features=4,
                            n_informative=2,
                            shuffle=False,
                            random_state=0)

In [32]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.33, random_state=42)

In [33]:
from sklearn.ensemble import AdaBoostRegressor, GradientBoostingRegressor

In [34]:
ada_regressor = AdaBoostRegressor()

In [35]:
ada_regressor.fit(X_train,y_train)

AdaBoostRegressor()

In [36]:
y_pred = ada_regressor.predict(X_test)

In [37]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [38]:
import numpy as np
mae = mean_absolute_error(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)
r2s = r2_score(y_test,y_pred)
mae,mse,rmse,r2s

(17.945442364374827, 572.0615616785884, 23.917808463121958, 0.9233136762015052)

In [39]:
gb_regressor = GradientBoostingRegressor()

In [40]:
gb_regressor.fit(X_train, y_train)

GradientBoostingRegressor()

In [41]:
y_pred = gb_regressor.predict(X_test)

In [42]:
mae = mean_absolute_error(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)
r2s = r2_score(y_test,y_pred)
mae,mse,rmse,r2s

(5.440922221575184, 66.51751067637656, 8.155826792936235, 0.9910831565976383)

In [43]:
xgb_regressor = xb.XGBRegressor()

In [44]:
xgb_regressor.fit(X_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [46]:
y_pred = xgb_regressor.predict(X_test)

In [47]:
mae = mean_absolute_error(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)
r2s = r2_score(y_test,y_pred)
mae,mse,rmse,r2s

(6.398100992754907, 101.1233812476291, 10.056012194087133, 0.9864441506344184)